
spring:
  application:
    name: agenda
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE:agenda}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWD:user}
    platform: Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 450
      minimum-idle: 50
      idle-timeout: 3000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        jdbc:
          time_zone: UTC
          batch_size: ${JBDC_BATCH_SIZE:50}
      type: trace
